### ISSUE TITLE
Where is the Character Voice

### ISSUE THREAD

**Issue by JiangShi-GitHub** [HaiKonofanDesu/konofan-assets-jp-sortet#3]

**Comment by HaiKonofanDesu** [comment]
https://github.com/HaiKonofanDesu/konofan-audio

**Comment by JiangShi-GitHub** [comment]
thanks，i also can't find the .moc file either, could you please tell me where it is



---- Replied Message ----
| From | Stefan ***@***.***> |
| Date | 03/08/2023 12:55 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [HaiKonofanDesu/konofan-assets-jp-sortet] Where is the Character Voice (Issue #3) |

https://github.com/HaiKonofanDesu/konofan-audio

**Comment by HaiKonofanDesu** [comment]
The Live2D Stuff is not yet in the GitHub. Still trying to figure out how to automatically extract them out of the Assetsbundles and how the whole Live2D lib works so I can provide a Live2D Viewer to see all the animations there as well. But since time is pretty rare atm this is currently on hold. I hope I can get back to work on that sooner or later

**Comment by HaiKonofanDesu** [comment]
Thanks for the idea, sadly this is pretty much what I do already and the whole "find which bundles have the files" is the annoying part.
